# kick: 1

version: 2.1

commands:
  run_tests:
    description: "Build the library and run the test suite"
    parameters:
      version:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
          - v1-dependencies-<< parameters.version >>-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
      - run: npm test
jobs:
  node-21:
    docker:
      - image: cimg/node:21.6
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "15"
  node-20:
    docker:
      - image: cimg/node:20.10
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "14"
  node-18:
    docker:
      - image: cimg/node:18.18
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "12"

workflows:
  build:
    jobs:
      - node-21
      - node-20
      - node-18
